In [82]:
!pip install fuzzywuzzy
!pip install geopy
import pandas as pd
import numpy as np
from geopy.distance import geodesic
import re


# 1. Drop duplicate census tracts
# 2. Standardize state names across all datasets
# 3. Convert lat/lon to census tract IDs (use census geocoder or shapefile)
# 4. Handle missing MW/power data (many "Unknown" values)
# 5. Standardize TRUE/FALSE/Yes/No to boolean
# 6. Extract numeric values from strings (e.g., "$14 billion" → 14000000000)
# 7. Validate geographic matches (some may fall outside census boundaries)

Requirement already satisfied: fuzzywuzzy in /Users/zdiener/data-center-classification/.venv/lib/python3.12/site-packages (0.18.0)
Requirement already satisfied: geopy in /Users/zdiener/data-center-classification/.venv/lib/python3.12/site-packages (2.4.1)
Requirement already satisfied: geographiclib<3,>=1.52 in /Users/zdiener/data-center-classification/.venv/lib/python3.12/site-packages (from geopy) (2.1)

In [83]:

# Load datasets
dc_osdc = pd.read_csv('/Users/zdiener/data-center-classification/data/raw/im3_open_source_data_center_atlas.csv')  # Dataset 1
dc_frac = pd.read_csv('/Users/zdiener/data-center-classification/data/raw/Data_Centers_Database - FracTracker Data Centers.csv')  # Dataset 2
dc_frac.head()

,facility_name,address,city,state,zip,county,lat,long,status,location_confidence,...,info_source_1,info_source_2,info_source_3,info_source_4,info_source_5,info_source_6,info_source_7,info_source_8,date_created,date_updated
0,Project Marvel,Rock Mountain Lake Rd,Bessemer,AL,35022.0,Jefferson,33.342000,-87.034100,Proposed,High,...,https://www.datacenterdynamics.com/en/news/700...,https://www.youtube.com/watch?v=ICSrvQ7meow&ab...,https://www.al.com/news/2025/06/14-billion-pro...,https://www.wbrc.com/2025/09/14/bessemer-resid...,https://www.wbrc.com/2025/11/19/bessemer-city-...,https://www.datacenterdynamics.com/en/news/ala...,https://abc3340.com/news/abc-3340-news-iteam/b...,NaN,09/16/2025,03/13/2026
1,DC Blox,433 6th St S,Birmingham,AL,35233.0,Jefferson,33.500510,-86.821000,Operating,High,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,08/25/2025,08/25/2025
2,Google Data Center,48809 Alabama 277,Bridgeport,AL,35740.0,Jackson,34.920190,-85.744600,Operating,High,...,https://www.madeinalabama.com/2018/04/google-k...,https://claycorp.com/work/mission-critical,NaN,NaN,NaN,NaN,NaN,NaN,07/15/2025,02/18/2026
3,Western Hospitality Partners Data Center,Childersburg Industrial Park,Childersburg,AL,35044.0,Talladega,33.340885,-86.336205,Proposed,Medium,...,https://www.datacenterdynamics.com/en/news/pla...,https://www.childersburg.org/childersburg-indu...,https://abc3340.com/news/local/concerns-grow-i...,NaN,NaN,NaN,NaN,NaN,01/26/2026,05/03/2026
4,DC Blox,333 Diamond Dr NW,Huntsville,AL,35806.0,Madison,34.710030,-86.693000,Operating,High,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,08/25/2025,08/25/2025

In [84]:
dc_frac.info()

<class 'pandas.DataFrame'>
RangeIndex: 1493 entries, 0 to 1492
Data columns (total 44 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   facility_name              1492 non-null   str
 1   address                    1435 non-null   str
 2   city                       1489 non-null   str
 3   state                      1493 non-null   str
 4   zip                        1443 non-null   float64
 5   county                     1492 non-null   str
 6   lat                        1493 non-null   float64
 7   long                       1493 non-null   float64
 8   status                     1493 non-null   str
 9   location_confidence        1493 non-null   str
 10  purpose                    64 non-null     str
 11  operator_name              815 non-null    str
 12  tenant                     26 non-null     str
 13  mw                         544 non-null    str
 14  sizerank                   1493 non-null   str
 15  power_source               93 non-null     str
 16  dedicated_power_plant      26 non-null     str
 17  number_of_generators       11 non-null     str
 18  number_of_buildings        168 non-null    str
 19  cooling_source             40 non-null     str
 20  cooling_type               42 non-null     str
 21  facility_size_sqft         902 non-null    str
 22  property_size_acres        860 non-null    float64
 23  project_cost               237 non-null    str
 24  expected_date_online       101 non-null    str
 25  community_pushback         1480 non-null   str
 26  advocacy_information       59 non-null     str
 27  resistance_status          41 non-null     str
 28  nda                        6 non-null      str
 29  community_group_website_1  98 non-null     str
 30  community_group_website_2  22 non-null     str
 31  petition_url               90 non-null     str
 32  other_info                 561 non-null    str
 33  information_source         1493 non-null   str
 34  info_source_1              1371 non-null   str
 35  info_source_2              664 non-null    str
 36  info_source_3              245 non-null    str
 37  info_source_4              112 non-null    str
 38  info_source_5              59 non-null     str
 39  info_source_6              38 non-null     str
 40  info_source_7              24 non-null     str
 41  info_source_8              12 non-null     str
 42  date_created               1489 non-null   str
 43  date_updated               1490 non-null   str
dtypes: float64(4), str(40)
memory usage: 513.3 KB

In [85]:
dc_osdc.info()

<class 'pandas.DataFrame'>
RangeIndex: 1242 entries, 0 to 1241
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         1242 non-null   int64
 1   state      1242 non-null   str
 2   state_abb  1242 non-null   str
 3   state_id   1242 non-null   int64
 4   county     1242 non-null   str
 5   county_id  1242 non-null   int64
 6   operator   784 non-null    str
 7   ref        327 non-null    str
 8   name       1029 non-null   str
 9   sqft       1149 non-null   float64
 10  lon        1242 non-null   float64
 11  lat        1242 non-null   float64
 12  type       1242 non-null   str
dtypes: float64(3), int64(3), str(7)
memory usage: 126.3 KB

In [86]:
print("="*60)
print("OSDC DATASET INITIAL ASSESSMENT")
print("="*60)
print(f"\nShape: {dc_osdc.shape}")
print(f"\nColumns: {list(dc_osdc.columns)}")
print(f"\nData types:\n{dc_osdc.dtypes}")
print(f"\nMissing values:\n{dc_osdc.isnull().sum()}")
print(f"\nDuplicate rows: {dc_osdc.duplicated().sum()}")
print(f"\nSample data:")
print(dc_osdc.head(3))

print("\n" + "="*60)
print("FRACTRACKER DATASET INITIAL ASSESSMENT")
print("="*60)
print(f"\nShape: {dc_frac.shape}")
print(f"\nColumns: {list(dc_frac.columns)}")
print(f"\nData types:\n{dc_frac.dtypes}")
print(f"\nMissing values:\n{dc_frac.isnull().sum()}")
print(f"\nDuplicate rows: {dc_frac.duplicated().sum()}")
print(f"\nSample data:")
print(dc_frac.head(3))

============================================================
OSDC DATASET INITIAL ASSESSMENT
============================================================

Shape: (1242, 13)

Columns: ['id', 'state', 'state_abb', 'state_id', 'county', 'county_id', 'operator', 'ref', 'name', 'sqft', 'lon', 'lat', 'type']

Data types:
id             int64
state            str
state_abb        str
state_id       int64
county           str
county_id      int64
operator         str
ref              str
name             str
sqft         float64
lon          float64
lat          float64
type             str
dtype: object

Missing values:
id             0
state          0
state_abb      0
state_id       0
county         0
county_id      0
operator     458
ref          915
name         213
sqft          93
lon            0
lat            0
type           0
dtype: int64

Duplicate rows: 0

Sample data:
        id           state state_abb  state_id            county  county_id  \
0  2744301      New Jersey        NJ        34  Middlesex County         23
1  7805491            Ohio        OH        39   Franklin County         49
2  9474864  North Carolina        NC        37   Caldwell County         27

  operator  ref                                    name       sqft        lon  \
0      NaN  NaN                                 Verizon   105786.0 -74.496521
1      NaN  NaN  Discover Financial Services New Albany   188209.0 -82.814358
2   Google  NaN                      Google Data Center  3407194.0 -81.546515

         lat      type
0  40.544256  building
1  40.100657  building
2  35.894738    campus

============================================================
FRACTRACKER DATASET INITIAL ASSESSMENT
============================================================

Shape: (1493, 44)

Columns: ['facility_name', 'address', 'city', 'state', 'zip', 'county', 'lat', 'long', 'status', 'location_confidence', 'purpose', 'operator_name', 'tenant', 'mw', 'sizerank', 'power_source', 'dedicated_power_plant', 'number_of_generators', 'number_of_buildings', 'cooling_source', 'cooling_type', 'facility_size_sqft', 'property_size_acres', 'project_cost', 'expected_date_online', 'community_pushback', 'advocacy_information', 'resistance_status', 'nda', 'community_group_website_1', 'community_group_website_2', 'petition_url', 'other_info', 'information_source', 'info_source_1', 'info_source_2', 'info_source_3', 'info_source_4', 'info_source_5', 'info_source_6', 'info_source_7', 'info_source_8', 'date_created', 'date_updated']

Data types:
facility_name                    str
address                          str
city                             str
state                            str
zip                          float64
county                           str
lat                          float64
long                         float64
status                           str
location_confidence              str
purpose                          str
operator_name                    str
tenant                           str
mw                               str
sizerank                         str
power_source                     str
dedicated_power_plant            str
number_of_generators             str
number_of_buildings              str
cooling_source                   str
cooling_type                     str
facility_size_sqft               str
property_size_acres          float64
project_cost                     str
expected_date_online             str
community_pushback               str
advocacy_information             str
resistance_status                str
nda                              str
community_group_website_1        str
community_group_website_2        str
petition_url                     str
other_info                       str
information_source               str
info_source_1                    str
info_source_2                    str
info_source_3                    str
info_source_4                    str
info_source_5                    str
info_source_6                    str
info_source_7                    str
info_source_8                    str
date_created                     str
date_updated                     str
dtype: object

Missing values:
facility_name                   1
address                        58
city                            4
state                           0
zip                            50
county                          1
lat                             0
long                            0
status                          0
location_confidence             0
purpose                      1429
operator_name                 678
tenant                       1467
mw                            949
sizerank                        0
power_source                 1400
dedicated_power_plant        1467
number_of_generators         1482
number_of_buildings          1325
cooling_source               1453
cooling_type                 1451
facility_size_sqft            591
property_size_acres           633
project_cost                 1256
expected_date_online         1392
community_pushback             13
advocacy_information         1434
resistance_status            1452
nda                          1487
community_group_website_1    1395
community_group_website_2    1471
petition_url                 1403
other_info                    932
information_source              0
info_source_1                 122
info_source_2                 829
info_source_3                1248
info_source_4                1381
info_source_5                1434
info_source_6                1455
info_source_7                1469
info_source_8                1481
date_created                    4
date_updated                    3
dtype: int64

Duplicate rows: 1

Sample data:
        facility_name                address        city state      zip  \
0      Project Marvel  Rock Mountain Lake Rd    Bessemer    AL  35022.0
1             DC Blox           433 6th St S  Birmingham    AL  35233.0
2  Google Data Center      48809 Alabama 277  Bridgeport    AL  35740.0

      county       lat     long     status location_confidence  ...  \
0  Jefferson  33.34200 -87.0341   Proposed                High  ...
1  Jefferson  33.50051 -86.8210  Operating                High  ...
2    Jackson  34.92019 -85.7446  Operating                High  ...

                                       info_source_1  \
0  https://www.datacenterdynamics.com/en/news/700...
1                                                NaN
2  https://www.madeinalabama.com/2018/04/google-k...

                                       info_source_2  \
0  https://www.youtube.com/watch?v=ICSrvQ7meow&ab...
1                                                NaN
2         https://claycorp.com/work/mission-critical

                                       info_source_3  \
0  https://www.al.com/news/2025/06/14-billion-pro...
1                                                NaN
2                                                NaN

                                       info_source_4  \
0  https://www.wbrc.com/2025/09/14/bessemer-resid...
1                                                NaN
2                                                NaN

                                       info_source_5  \
0  https://www.wbrc.com/2025/11/19/bessemer-city-...
1                                                NaN
2                                                NaN

                                       info_source_6  \
0  https://www.datacenterdynamics.com/en/news/ala...
1                                                NaN
2                                                NaN

                                       info_source_7 info_source_8  \
0  https://abc3340.com/news/abc-3340-news-iteam/b...           NaN
1                                                NaN           NaN
2                                                NaN           NaN

  date_created date_updated
0   09/16/2025   03/13/2026
1   08/25/2025   08/25/2025
2   07/15/2025   02/18/2026

[3 rows x 44 columns]

In [87]:
# A more detailed assessment of each dataset to identify specific cleaning needs.
# 1. Check coordinate validity
print("\n1. COORDINATE VALIDATION:")
print(f"   Latitude range: {dc_osdc['lat'].min():.4f} to {dc_osdc['lat'].max():.4f}")
print(f"   Longitude range: {dc_osdc['lon'].min():.4f} to {dc_osdc['lon'].max():.4f}")
invalid_coords = dc_osdc[
    (dc_osdc['lat'] < 24) | (dc_osdc['lat'] > 50) |
    (dc_osdc['lon'] < -125) | (dc_osdc['lon'] > -65)
]
print(f"   Records with potentially invalid US coordinates: {len(invalid_coords)}")
if len(invalid_coords) > 0:
    print(invalid_coords[['id', 'name', 'state', 'lat', 'lon']].head())

# 2. Check state consistency
print("\n2. STATE DATA:")
print(f"   Unique states: {dc_osdc['state'].nunique()}")
print(f"   Missing state: {dc_osdc['state'].isnull().sum()}")
print(f"   Missing state_abb: {dc_osdc['state_abb'].isnull().sum()}")
print(f"   State distribution (top 10):")
print(dc_osdc['state'].value_counts().head(10))

# 3. Check name/operator data
print("\n3. NAME & OPERATOR DATA:")
print(f"   Missing names: {dc_osdc['name'].isnull().sum()}")
print(f"   Missing operators: {dc_osdc['operator'].isnull().sum()}")
print(f"   Unique operators (non-null): {dc_osdc['operator'].nunique()}")
print(f"   Top operators:")
print(dc_osdc['operator'].value_counts().head(10))

# Look at records with missing names
print(f"\n   Sample records with missing names:")
print(dc_osdc[dc_osdc['name'].isnull()][['id', 'operator', 'state', 'county', 'type']].head())

# 4. Check size data
print("\n4. FACILITY SIZE DATA:")
print(f"   Missing sqft: {dc_osdc['sqft'].isnull().sum()}")
print(f"   Sqft statistics:")
print(dc_osdc['sqft'].describe())
unrealistic_size = dc_osdc[(dc_osdc['sqft'] < 1000) | (dc_osdc['sqft'] > 10000000)]
print(f"   Potentially unrealistic sizes (<1k or >10M sqft): {len(unrealistic_size)}")
if len(unrealistic_size) > 0:
    print(unrealistic_size[['name', 'operator', 'sqft', 'type']].head())

# 5. Check type field
print("\n5. TYPE FIELD:")
print(f"   Unique types: {dc_osdc['type'].unique()}")
print(f"   Type distribution:")
print(dc_osdc['type'].value_counts())

# 6. Check for duplicates by coordinates
print("\n6. DUPLICATE COORDINATE ANALYSIS:")
dup_coords = dc_osdc.groupby(['lat', 'lon']).size()
print(f"   Unique coordinate pairs: {len(dup_coords)}")
print(f"   Facilities with same coordinates: {len(dup_coords[dup_coords > 1])}")
if len(dup_coords[dup_coords > 1]) > 0:
    print("   Examples of shared coordinates:")
    for coords, count in dup_coords[dup_coords > 1].head(3).items():
        print(f"\n      Location {coords}: {count} facilities")
        print(dc_osdc[(dc_osdc['lat'] == coords[0]) & (dc_osdc['lon'] == coords[1])][['id', 'name', 'operator', 'type']])

print("\n" + "="*60)
print("FRACTRACKER DATASET - DETAILED CLEANING ASSESSMENT")
print("="*60)

# 1. Check coordinate validity
print("\n1. COORDINATE VALIDATION:")
print(f"   Latitude range: {dc_frac['lat'].min():.4f} to {dc_frac['lat'].max():.4f}")
print(f"   Longitude range: {dc_frac['long'].min():.4f} to {dc_frac['long'].max():.4f}")
print(f"   Missing coordinates: lat={dc_frac['lat'].isnull().sum()}, long={dc_frac['long'].isnull().sum()}")
invalid_coords_frac = dc_frac[
    (dc_frac['lat'] < 24) | (dc_frac['lat'] > 50) |
    (dc_frac['long'] < -125) | (dc_frac['long'] > -65)
]
print(f"   Records with potentially invalid US coordinates: {len(invalid_coords_frac)}")
if len(invalid_coords_frac) > 0:
    print(invalid_coords_frac[['facility_name', 'state', 'lat', 'long']].head())

# 2. Check state data
print("\n2. STATE DATA:")
print(f"   Unique states: {dc_frac['state'].nunique()}")
print(f"   Missing state: {dc_frac['state'].isnull().sum()}")
print(f"   State distribution:")
print(dc_frac['state'].value_counts())

# 3. Check facility status
print("\n3. FACILITY STATUS:")
print(f"   Missing status: {dc_frac['status'].isnull().sum()}")
print(f"   Status values:")
print(dc_frac['status'].value_counts())

# 4. Check power data (mw is string type!)
print("\n4. POWER DATA (MW):")
print(f"   Missing MW: {dc_frac['mw'].isnull().sum()}")
print(f"   Unique MW values (sample of 20):")
print(dc_frac['mw'].value_counts().head(20))

# 5. Check size data
print("\n5. SIZE DATA:")
print(f"   Missing facility_size_sqft: {dc_frac['facility_size_sqft'].isnull().sum()}")
print(f"   facility_size_sqft is STRING type - sample values:")
print(dc_frac['facility_size_sqft'].value_counts().head(10))

print(f"\n   Sizerank categories:")
print(dc_frac['sizerank'].value_counts())

# 6. Check EJ-relevant fields
print("\n6. ENVIRONMENTAL JUSTICE FIELDS:")
ej_fields = ['community_pushback', 'advocacy_information', 'resistance_status', 
             'community_group_website_1', 'petition_url']
for field in ej_fields:
    non_null = dc_frac[field].notna().sum()
    print(f"   {field}: {non_null} records ({non_null/len(dc_frac)*100:.1f}%)")

print(f"\n   Community pushback values:")
print(dc_frac['community_pushback'].value_counts(dropna=False))

print(f"\n   Resistance status values:")
print(dc_frac['resistance_status'].value_counts(dropna=False))

# 7. Check date fields
print("\n7. DATE FIELDS:")
print(f"   date_created samples:")
print(dc_frac['date_created'].value_counts().head(5))
print(f"\n   date_updated samples:")
print(dc_frac['date_updated'].value_counts().head(5))

# 8. Check location confidence
print("\n8. LOCATION CONFIDENCE:")
print(dc_frac['location_confidence'].value_counts(dropna=False))

# 9. Check for the duplicate row
print("\n9. DUPLICATE ROW:")
dup_mask = dc_frac.duplicated(keep=False)
if dup_mask.sum() > 0:
    print(f"   Found {dup_mask.sum()} duplicate rows:")
    print(dc_frac[dup_mask][['facility_name', 'city', 'state', 'operator_name']])

# 10. Check text fields for cleaning needs
print("\n10. TEXT FIELD CLEANING NEEDS:")
# Check for leading/trailing whitespace
print(f"   Facility names with leading/trailing spaces: {dc_frac['facility_name'].str.strip().ne(dc_frac['facility_name']).sum()}")
print(f"   Operator names with leading/trailing spaces: {dc_frac['operator_name'].str.strip().ne(dc_frac['operator_name']).sum()}")

# Check for missing facility names
print(f"\n   Records with missing facility_name:")
print(dc_frac[dc_frac['facility_name'].isnull()][['address', 'city', 'state', 'operator_name']])

# 11. Check numeric fields that are stored as strings
print("\n11. NUMERIC FIELDS STORED AS STRINGS:")
string_numeric_fields = ['mw', 'facility_size_sqft', 'number_of_generators', 'number_of_buildings']
for field in string_numeric_fields:
    if field in dc_frac.columns:
        print(f"\n   {field} - sample values:")
        print(dc_frac[field].value_counts().head(10))

1. COORDINATE VALIDATION:
   Latitude range: 18.4174 to 48.7573
   Longitude range: -123.3286 to -66.1090
   Records with potentially invalid US coordinates: 1
               id       name        state        lat       lon
1197  10014176940  Microsoft  Puerto Rico  18.417436 -66.10899

2. STATE DATA:
   Unique states: 46
   Missing state: 0
   Missing state_abb: 0
   State distribution (top 10):
state
Virginia      292
California     94
Oregon         94
Texas          92
Washington     81
Iowa           57
Ohio           56
Arizona        54
New Jersey     47
Illinois       41
Name: count, dtype: int64

3. NAME & OPERATOR DATA:
   Missing names: 213
   Missing operators: 458
   Unique operators (non-null): 129
   Top operators:
operator
Amazon Web Services            176
Digital Realty                  70
Meta                            61
Google                          60
Microsoft                       53
Flexential                      42
Equinix                         38
Quality Technology Services     24
CyrusOne                        21
NTT                             13
Name: count, dtype: int64

   Sample records with missing names:
          id          operator       state                 county      type
20  36897140               NaN        Ohio        Hamilton County  building
25  38305568       Centurylink  California     Santa Clara County  building
26  38305611           Vantage  California     Santa Clara County  building
31  45583050               NaN    Virginia  Prince William County  building
53  71187940  Verizon Wireless    Michigan           Wayne County  building

4. FACILITY SIZE DATA:
   Missing sqft: 93
   Sqft statistics:
count    1.149000e+03
mean     4.742561e+05
std      1.971704e+06
min      2.040000e+02
25%      5.809500e+04
50%      1.323880e+05
75%      2.319240e+05
max      2.659752e+07
Name: sqft, dtype: float64
   Potentially unrealistic sizes (<1k or >10M sqft): 17
                               name   operator        sqft      type
3                  Project Alluvion  Microsoft  10962475.0    campus
9       Meta Huntsville Data Center       Meta  14138187.0    campus
267                   QES Computers        NaN       941.0  building
375  Facebook Prineville Datacenter       Meta  15867920.0    campus
451    Facebook Altoona Data Center   Facebook  20353917.0    campus

5. TYPE FIELD:

   Unique types: <StringArray>
['building', 'campus', 'point']
Length: 3, dtype: str
   Type distribution:
type
building    1040
campus       109
point         93
Name: count, dtype: int64

6. DUPLICATE COORDINATE ANALYSIS:
   Unique coordinate pairs: 1240
   Facilities with same coordinates: 2
   Examples of shared coordinates:

      Location (33.746561602113815, -84.57973805393436): 2 facilities
            id                          name        operator      type
773  975064000  Digital Realty Atlanta ATL11  Digital Realty  building
774  975064000  Digital Realty Atlanta ATL11  Digital Realty  building

      Location (41.4982126945884, -93.78856494092211): 2 facilities
            id            name   operator    type
683  830885779  Project Osmium  Microsoft  campus
684  830885779  Project Osmium  Microsoft  campus

============================================================
FRACTRACKER DATASET - DETAILED CLEANING ASSESSMENT
============================================================

1. COORDINATE VALIDATION:
   Latitude range: 21.4805 to 48.2220
   Longitude range: -158.0214 to 92.4045
   Missing coordinates: lat=0, long=0
   Records with potentially invalid US coordinates: 3
                 facility_name state        lat       long
1339  Mililani Technology Park    HI  21.480452 -158.02138
1475  Grant County Data Center    AK  34.306500   92.40450
1478   Wilsonville Data Center    AL  33.257000   86.49500

2. STATE DATA:
   Unique states: 50
   Missing state: 0
   State distribution:
state
VA     452
TX     181
GA     175
PA     100
OH      57
IN      37
NY      35
IL      31
AZ      29
NC      28
CA      25
MO      25
MI      23
IA      19
OR      19
WA      18
WI      17
MD      15
NV      15
KY      13
NJ      11
OK      11
UT      11
MN      10
SC      10
TN      10
AL       9
NM       9
WV       9
CO       8
FL       8
LA       8
MS       8
NE       8
AR       6
KS       6
ND       6
MA       5
MT       5
WY       5
CT       3
ME       3
SD       3
DE       1
ID       1
HI       1
NH       1
AK       1
BA       1
OH       1
Name: count, dtype: int64

3. FACILITY STATUS:
   Missing status: 0
   Status values:
status
Proposed                                 680
Operating                                529
Approved/Permitted/Under construction    136
Expanding                                 52
Suspended                                 49
Cancelled                                 46
Unknown                                    1
Name: count, dtype: int64

4. POWER DATA (MW):
   Missing MW: 949
   Unique MW values (sample of 20):
mw
300     21
200     19
100     16
2       12
4       12
500     11
1000    11
10      10
600     10
150      9
1500     8
12       8
30       8
1200     7
32       7
50       7
72       6
36       6
20       6
48       6
Name: count, dtype: int64

5. SIZE DATA:
   Missing facility_size_sqft: 591
   facility_size_sqft is STRING type - sample values:
facility_size_sqft
1,000,000    24
1,800,000    10
500,000      10
2,000,000     9
2,200,000     9
1,500,000     8
300,000       8
250,000       8
2,100,000     8
1,600,000     8
Name: count, dtype: int64

   Sizerank categories:
sizerank
Unknown                    851
Hyperscale (100-999 MW)    311
Medium (11-50 MW)          105
Mega campus (>1,000 MW)     98
Small (0-10 MW)             95
Large (51-99 MW)            32
Hyperscale (101-999 MW)      1
Name: count, dtype: int64

6. ENVIRONMENTAL JUSTICE FIELDS:
   community_pushback: 1480 records (99.1%)
   advocacy_information: 59 records (4.0%)
   resistance_status: 41 records (2.7%)
   community_group_website_1: 98 records (6.6%)
   petition_url: 90 records (6.0%)

   Community pushback values:
community_pushback
Unknown    1268
Yes         211
NaN          13
Yes           1
Name: count, dtype: int64

   Resistance status values:
resistance_status
NaN                   1452
Organized Advocacy      32
Emerging Concern         8
Unknown                  1
Name: count, dtype: int64

7. DATE FIELDS:
   date_created samples:
date_created
04/10/2024    252
10/16/2025    110
08/05/2025     54
08/06/2025     39
11/24/2025     31
Name: count, dtype: int64

   date_updated samples:
date_updated
10/17/2025    352
10/16/2025    100
08/05/2025     49
02/10/2026     32
11/24/2025     30
Name: count, dtype: int64

8. LOCATION CONFIDENCE:
location_confidence
High       1188
Medium      250
Low          49
Medium        3
High          2
high          1
Name: count, dtype: int64

9. DUPLICATE ROW:
   Found 2 duplicate rows:
           facility_name                city state operator_name
1482  Switch data center  Big Beaver Borough    PA           NaN
1483  Switch data center  Big Beaver Borough    PA           NaN

10. TEXT FIELD CLEANING NEEDS:
   Facility names with leading/trailing spaces: 18
   Operator names with leading/trailing spaces: 686

   Records with missing facility_name:
          address      city state    operator_name
1485  39.03692204  Leesburg    BA  Curata Partners

11. NUMERIC FIELDS STORED AS STRINGS:

   mw - sample values:
mw
300     21
200     19
100     16
2       12
4       12
500     11
1000    11
10      10
600     10
150      9
Name: count, dtype: int64

   facility_size_sqft - sample values:
facility_size_sqft
1,000,000    24
1,800,000    10
500,000      10
2,000,000     9
2,200,000     9
1,500,000     8
300,000       8
250,000       8
2,100,000     8
1,600,000     8
Name: count, dtype: int64

   number_of_generators - sample values:
number_of_generators
100 natural gas-powered backup emergency generators connected to Southern California Gas Company’s high-pressure gas line    1
25 2.5MW emergency generators for redundancy purposes                                                                        1
516                                                                                                                          1
0                                                                                                                            1
12-24                                                                                                                        1
12                                                                                                                           1
14 on-site diesel generators                                                                                                 1
1.2 GW diesel                                                                                                                1
115 diesel-fueled generators                                                                                                 1
6                                                                                                                            1
Name: count, dtype: int64

   number_of_buildings - sample values:
number_of_buildings
2     22
3     22
6     21
4     14
5      9
7      9
10     8
12     7
8      6
9      5
Name: count, dtype: int64

In [88]:
dc_osdc.head()

,id,state,state_abb,state_id,county,county_id,operator,ref,name,sqft,lon,lat,type
0,2744301,New Jersey,NJ,34,Middlesex County,23,NaN,NaN,Verizon,105786.0,-74.496521,40.544256,building
1,7805491,Ohio,OH,39,Franklin County,49,NaN,NaN,Discover Financial Services New Albany,188209.0,-82.814358,40.100657,building
2,9474864,North Carolina,NC,37,Caldwell County,27,Google,NaN,Google Data Center,3407194.0,-81.546515,35.894738,campus
3,13924557,Iowa,IA,19,Polk County,153,Microsoft,NaN,Project Alluvion,10962475.0,-93.711719,41.515955,campus
4,14593270,North Carolina,NC,37,Catawba County,35,NaN,NaN,Apple - Maiden Data Center,5431080.0,-81.261809,35.588771,campus

In [89]:
def clean_fractracker(df):
    """
    Clean FracTracker dataset
    """
    df_clean = df.copy()
    
    print("Starting FracTracker cleaning...")
    print(f"Initial shape: {df_clean.shape}")
    
    # 1. REMOVE DUPLICATE ROWS
    print("\n1. Removing duplicates...")
    initial_count = len(df_clean)
    df_clean = df_clean.drop_duplicates()
    print(f"   Removed {initial_count - len(df_clean)} duplicate rows")
    
    # 2. STANDARDIZE LOCATION CONFIDENCE
    print("\n2. Standardizing location_confidence...")
    confidence_map = {
        'High': 'High',
        'high': 'High',
        'Medium': 'Medium',
        'Medium ': 'Medium',  # trailing space
        'Low': 'Low'
    }
    df_clean['location_confidence'] = df_clean['location_confidence'].map(confidence_map)
    print(f"   Values after standardization:")
    print(f"   {df_clean['location_confidence'].value_counts()}")
    
    # 3. STRIP WHITESPACE FROM TEXT FIELDS
    print("\n3. Stripping whitespace from text fields...")
    text_fields = ['facility_name', 'address', 'city', 'county', 'operator_name', 
                   'status', 'purpose', 'tenant', 'advocacy_information', 
                   'community_pushback', 'resistance_status']
    for field in text_fields:
        if field in df_clean.columns:
            df_clean[field] = df_clean[field].str.strip()
    print(f"   Whitespace stripped from {len(text_fields)} fields")
    
    # 4. CLEAN COMMUNITY_PUSHBACK - Replace "Unknown" with NaN
    print("\n4. Cleaning community_pushback field...")
    print(f"   Values before cleaning:")
    print(f"   {df_clean['community_pushback'].value_counts(dropna=False)}")
    
    # Replace "Unknown" (case-insensitive) with NaN
    df_clean['community_pushback'] = df_clean['community_pushback'].replace({
        'Unknown': np.nan,
        'unknown': np.nan,
        'UNKNOWN': np.nan
    })
    
    print(f"   Values after cleaning:")
    print(f"   {df_clean['community_pushback'].value_counts(dropna=False)}")
    
    # 5. STANDARDIZE SIZERANK
    print("\n5. Standardizing sizerank...")
    # Fix the inconsistency: "Hyperscale (101-999 MW)" -> "Hyperscale (100-999 MW)"
    df_clean['sizerank'] = df_clean['sizerank'].replace({
        'Hyperscale (101-999 MW)': 'Hyperscale (100-999 MW)'
    })
    print(f"   Sizerank values after standardization:")
    print(f"   {df_clean['sizerank'].value_counts()}")
    
    # 6. CLEAN MW FIELD (convert string to numeric)
    print("\n6. Cleaning MW field...")
    def parse_mw(mw_str):
        """Extract numeric MW value from string"""
        if pd.isna(mw_str):
            return np.nan
        
        mw_str = str(mw_str).strip()
        
        # Handle ranges (e.g., "100-200", "150-1,000")
        range_match = re.search(r'(\d+(?:,\d+)?)\s*-\s*(\d+(?:,\d+)?)', mw_str)
        if range_match:
            # Take the midpoint of the range
            low = float(range_match.group(1).replace(',', ''))
            high = float(range_match.group(2).replace(',', ''))
            return (low + high) / 2
        
        # Extract first number found
        number_match = re.search(r'(\d+(?:,\d+)*(?:\.\d+)?)', mw_str)
        if number_match:
            return float(number_match.group(1).replace(',', ''))
        
        return np.nan
    
    df_clean['mw_numeric'] = df_clean['mw'].apply(parse_mw)
    df_clean['mw_original'] = df_clean['mw']  # Keep original for reference
    print(f"   Converted {df_clean['mw_numeric'].notna().sum()} MW values to numeric")
    if df_clean['mw_numeric'].notna().sum() > 0:
        print(f"   MW range: {df_clean['mw_numeric'].min():.1f} to {df_clean['mw_numeric'].max():.1f}")
    
    # 7. CLEAN FACILITY_SIZE_SQFT (convert string to numeric)
    print("\n7. Cleaning facility_size_sqft...")
    def parse_sqft(sqft_str):
        """Extract numeric sqft value from string"""
        if pd.isna(sqft_str):
            return np.nan
        
        sqft_str = str(sqft_str).strip()
        
        # Remove commas and extract number
        number_match = re.search(r'(\d+(?:,\d+)*(?:\.\d+)?)', sqft_str)
        if number_match:
            return float(number_match.group(1).replace(',', ''))
        
        return np.nan
    
    df_clean['facility_size_sqft_numeric'] = df_clean['facility_size_sqft'].apply(parse_sqft)
    df_clean['facility_size_sqft_original'] = df_clean['facility_size_sqft']  # Keep original
    print(f"   Converted {df_clean['facility_size_sqft_numeric'].notna().sum()} sqft values to numeric")
    if df_clean['facility_size_sqft_numeric'].notna().sum() > 0:
        print(f"   Sqft range: {df_clean['facility_size_sqft_numeric'].min():.0f} to {df_clean['facility_size_sqft_numeric'].max():.0f}")
    
    # 8. CLEAN NUMBER_OF_GENERATORS
    print("\n8. Cleaning number_of_generators...")
    def parse_generators(gen_str):
        """Extract numeric generator count from string"""
        if pd.isna(gen_str):
            return np.nan
        
        gen_str = str(gen_str).strip()
        
        # Handle ranges (e.g., "12-24")
        range_match = re.search(r'^(\d+)\s*-\s*(\d+)$', gen_str)
        if range_match:
            low = int(range_match.group(1))
            high = int(range_match.group(2))
            return (low + high) / 2
        
        # Extract first number
        number_match = re.search(r'(\d+)', gen_str)
        if number_match:
            return int(number_match.group(1))
        
        return np.nan
    
    df_clean['number_of_generators_numeric'] = df_clean['number_of_generators'].apply(parse_generators)
    df_clean['number_of_generators_original'] = df_clean['number_of_generators']  # Keep original
    print(f"   Converted {df_clean['number_of_generators_numeric'].notna().sum()} generator values to numeric")
    
    # 9. CLEAN NUMBER_OF_BUILDINGS
    print("\n9. Cleaning number_of_buildings...")
    def parse_buildings(bldg_str):
        """Extract numeric building count from string"""
        if pd.isna(bldg_str):
            return np.nan
        
        bldg_str = str(bldg_str).strip()
        
        # Extract first number
        number_match = re.search(r'(\d+)', bldg_str)
        if number_match:
            return int(number_match.group(1))
        
        return np.nan
    
    df_clean['number_of_buildings_numeric'] = df_clean['number_of_buildings'].apply(parse_buildings)
    df_clean['number_of_buildings_original'] = df_clean['number_of_buildings']  # Keep original
    print(f"   Converted {df_clean['number_of_buildings_numeric'].notna().sum()} building values to numeric")
    
    # 10. PARSE DATE FIELDS
    print("\n10. Parsing date fields...")
    df_clean['date_created_parsed'] = pd.to_datetime(df_clean['date_created'], format='%m/%d/%Y', errors='coerce')
    df_clean['date_updated_parsed'] = pd.to_datetime(df_clean['date_updated'], format='%m/%d/%Y', errors='coerce')
    print(f"   Parsed {df_clean['date_created_parsed'].notna().sum()} created dates")
    print(f"   Parsed {df_clean['date_updated_parsed'].notna().sum()} updated dates")
    
    # 11. FIX MISSING FACILITY NAME
    print("\n11. Handling missing facility names...")
    # For the row with coordinates as facility_name
    mask_bad_name = df_clean['facility_name'].str.match(r'^\d+\.\d+$', na=False)
    if mask_bad_name.any():
        print(f"   Found {mask_bad_name.sum()} records with coordinates as facility_name")
        # Use operator name or create placeholder
        df_clean.loc[mask_bad_name, 'facility_name'] = df_clean.loc[mask_bad_name, 'operator_name'].fillna('Unknown Facility')
    
    # Handle truly missing facility names
    missing_names = df_clean['facility_name'].isna()
    if missing_names.any():
        print(f"   Found {missing_names.sum()} records with missing facility_name")
        df_clean.loc[missing_names, 'facility_name'] = df_clean.loc[missing_names, 'operator_name'].fillna('Unknown Facility')
    
    # 12. VALIDATE COORDINATES AND CHECK STATE/COORDINATE CONSISTENCY
    print("\n12. Validating coordinates...")
    
    # Define expanded valid ranges for all US states and territories
    # Contiguous US: roughly 24-50°N, -125 to -65°W
    # Alaska: 51-72°N, -180 to -130°W
    # Hawaii: 19-23°N, -161 to -154°W
    
    # Check for completely invalid coordinates (outside all US territories)
    invalid_coords = (
        (df_clean['lat'] < 18) | (df_clean['lat'] > 72) |  # Outside US latitude range
        (df_clean['long'] < -180) | (df_clean['long'] > -60)  # Outside US longitude range
    )
    
    if invalid_coords.any():
        print(f"   ERROR: {invalid_coords.sum()} records with invalid coordinates (outside US)")
        print(df_clean[invalid_coords][['facility_name', 'state', 'lat', 'long']])
    
    # Check for state/coordinate mismatches
    print("\n   Checking state/coordinate consistency...")
    
    # Define approximate state coordinate ranges
    state_bounds = {
        'HI': {'lat_min': 18, 'lat_max': 23, 'lon_min': -161, 'lon_max': -154},
        'AK': {'lat_min': 51, 'lat_max': 72, 'lon_min': -180, 'lon_max': -130},
        # Contiguous states
        'default': {'lat_min': 24, 'lat_max': 50, 'lon_min': -125, 'lon_max': -65}
    }
    
    def check_state_coord_mismatch(row):
        """Check if coordinates match the state"""
        state = row['state']
        lat = row['lat']
        lon = row['long']
        
        if state == 'HI':
            bounds = state_bounds['HI']
        elif state == 'AK':
            bounds = state_bounds['AK']
        else:
            bounds = state_bounds['default']
        
        in_range = (bounds['lat_min'] <= lat <= bounds['lat_max'] and 
                   bounds['lon_min'] <= lon <= bounds['lon_max'])
        
        return not in_range
    
    mismatches = df_clean.apply(check_state_coord_mismatch, axis=1)
    
    if mismatches.any():
        print(f"   WARNING: {mismatches.sum()} records with state/coordinate mismatches")
        print(df_clean[mismatches][['facility_name', 'state', 'county', 'lat', 'long']])
        print("\n   These may need manual review - coordinates might be correct but state code wrong, or vice versa")
    
    # 13. CREATE HELPER FLAGS
    print("\n13. Creating data quality flags...")
    df_clean['has_mw_data'] = df_clean['mw_numeric'].notna()
    df_clean['has_size_data'] = df_clean['facility_size_sqft_numeric'].notna()
    df_clean['has_ej_data'] = (
        df_clean['community_pushback'].notna() |
        df_clean['advocacy_information'].notna() |
        df_clean['resistance_status'].notna()
    )
    df_clean['has_community_pushback'] = df_clean['community_pushback'].notna()
    df_clean['is_proposed'] = df_clean['status'].str.contains('Proposed', case=False, na=False)
    df_clean['is_operating'] = df_clean['status'].str.contains('Operating', case=False, na=False)
    
    print(f"\nFinal shape: {df_clean.shape}")
    print(f"Records with MW data: {df_clean['has_mw_data'].sum()}")
    print(f"Records with size data: {df_clean['has_size_data'].sum()}")
    print(f"Records with EJ data: {df_clean['has_ej_data'].sum()}")
    print(f"Records with community pushback (Yes/No): {df_clean['has_community_pushback'].sum()}")
    
    return df_clean

In [92]:
# Run the cleaning
dc_frac_clean = clean_fractracker(dc_frac)

dc_frac_clean = dc_frac_clean.rename(columns={
    'long': 'longitude',
    'lat': 'latitude',
    'state': 'state_abb'  
})

# Save cleaned version
dc_frac_clean.to_csv('/Users/zdiener/data-center-classification/data/processed/fractracker_cleaned.csv', index=False)
print("\nCleaned FracTracker data saved to: data/processed/fractracker_cleaned.csv")

# Show summary of cleaned data
print("\n" + "="*60)
print("CLEANING SUMMARY")
print("="*60)
print(f"\nOriginal records: {len(dc_frac)}")
print(f"Cleaned records: {len(dc_frac_clean)}")
print(f"\nCommunity pushback breakdown:")
print(dc_frac_clean['community_pushback'].value_counts(dropna=False))

Starting FracTracker cleaning...
Initial shape: (1493, 44)

1. Removing duplicates...
   Removed 1 duplicate rows

2. Standardizing location_confidence...
   Values after standardization:
   location_confidence
High      1188
Medium     253
Low         48
Name: count, dtype: int64

3. Stripping whitespace from text fields...
   Whitespace stripped from 11 fields

4. Cleaning community_pushback field...
   Values before cleaning:
   community_pushback
Unknown    1268
Yes         212
NaN          12
Name: count, dtype: int64
   Values after cleaning:
   community_pushback
NaN    1280
Yes     212
Name: count, dtype: int64

5. Standardizing sizerank...
   Sizerank values after standardization:
   sizerank
Unknown                    850
Hyperscale (100-999 MW)    312
Medium (11-50 MW)          105
Mega campus (>1,000 MW)     98
Small (0-10 MW)             95
Large (51-99 MW)            32
Name: count, dtype: int64

6. Cleaning MW field...
   Converted 544 MW values to numeric
   MW range: 0.0 to 11000.0

7. Cleaning facility_size_sqft...
   Converted 902 sqft values to numeric
   Sqft range: 320 to 27878400

8. Cleaning number_of_generators...
   Converted 11 generator values to numeric

9. Cleaning number_of_buildings...
   Converted 167 building values to numeric

10. Parsing date fields...
   Parsed 1488 created dates
   Parsed 1487 updated dates

11. Handling missing facility names...
   Found 1 records with missing facility_name

12. Validating coordinates...
   ERROR: 2 records with invalid coordinates (outside US)
                 facility_name state      lat     long
1475  Grant County Data Center    AK  34.3065  92.4045
1478   Wilsonville Data Center    AL  33.2570  86.4950

   Checking state/coordinate consistency...
   WARNING: 2 records with state/coordinate mismatches
                 facility_name state  county      lat     long
1475  Grant County Data Center    AK   Grant  34.3065  92.4045
1478   Wilsonville Data Center    AL  Shleby  33.2570  86.4950

   These may need manual review - coordinates might be correct but state code wrong, or vice versa

13. Creating data quality flags...

Final shape: (1492, 60)
Records with MW data: 544
Records with size data: 902
Records with EJ data: 214
Records with community pushback (Yes/No): 212

Cleaned FracTracker data saved to: data/processed/fractracker_cleaned.csv

============================================================
CLEANING SUMMARY
============================================================

Original records: 1493
Cleaned records: 1492

Community pushback breakdown:
community_pushback
NaN    1280
Yes     212
Name: count, dtype: int64

### cleaning the ocsd dataset

In [93]:
def clean_osdc(df):
    """
    Clean OSDC (Open Source Data Center) dataset
    """
    df_clean = df.copy()
    
    print("Starting OSDC cleaning...")
    print(f"Initial shape: {df_clean.shape}")
    
    # 1. REMOVE DUPLICATE ROWS (if any)
    print("\n1. Checking for duplicates...")
    initial_count = len(df_clean)
    df_clean = df_clean.drop_duplicates()
    print(f"   Removed {initial_count - len(df_clean)} duplicate rows")
    
    # 2. STRIP WHITESPACE FROM TEXT FIELDS
    print("\n2. Stripping whitespace from text fields...")
    text_fields = ['state', 'state_abb', 'county', 'operator', 'ref', 'name', 'type']
    for field in text_fields:
        if field in df_clean.columns and df_clean[field].dtype == 'object':
            df_clean[field] = df_clean[field].str.strip()
    print(f"   Whitespace stripped from {len(text_fields)} fields")
    
    # 3. EXTRACT OPERATORS FROM FACILITY NAMES (before handling missing names)
    print("\n3. Extracting operators from facility names...")
    
    # Define patterns to extract operator names
    operator_patterns = {
        'Google': ['google', 'goog '],
        'Microsoft': ['microsoft', 'msft'],
        'Meta': ['meta', 'facebook', 'fb '],
        'Amazon': ['amazon', 'aws'],
        'Apple': ['apple'],
        'Oracle': ['oracle'],
        'IBM': ['ibm'],
        'Dell': ['dell'],
        'Equinix': ['equinix'],
        'Digital Realty': ['digital realty'],
        'CyrusOne': ['cyrusone', 'cyrus one'],
        'QTS': ['qts'],
        'Switch': ['switch'],
        'Cologix': ['cologix'],
        'CoreSite': ['coresite'],
        'Vantage': ['vantage'],
        'Iron Mountain': ['iron mountain'],
        'Aligned': ['aligned'],
        'EdgeConnex': ['edgeconnex'],
        'DataBank': ['databank'],
        'T5': ['t5 data'],
        'NTT': ['ntt'],
        'Telx': ['telx'],
        'Flexential': ['flexential'],
        'Cyxtera': ['cyxtera'],
        'Datacenter': ['datacenter', 'data center'],  # Generic pattern
    }
    
    def extract_operator_from_name(name):
        """Extract operator from facility name using pattern matching"""
        if pd.isna(name):
            return None
        
        name_lower = name.lower()
        
        # Check each operator pattern
        for operator, patterns in operator_patterns.items():
            for pattern in patterns:
                if pattern in name_lower:
                    # Don't use generic "datacenter" if we already have a better match
                    if operator == 'Datacenter':
                        continue
                    return operator
        
        return None
    
    # Count missing operators before extraction
    missing_before = df_clean['operator'].isnull().sum()
    
    # Extract operators from names where operator is missing
    mask_missing_operator = df_clean['operator'].isnull()
    df_clean.loc[mask_missing_operator, 'operator'] = df_clean.loc[mask_missing_operator, 'name'].apply(extract_operator_from_name)
    
    missing_after = df_clean['operator'].isnull().sum()
    extracted = missing_before - missing_after
    
    print(f"   Missing operators before: {missing_before}")
    print(f"   Extracted {extracted} operators from facility names")
    print(f"   Missing operators after: {missing_after}")
    
    if extracted > 0:
        print(f"\n   Sample extracted operators:")
        newly_filled = mask_missing_operator & df_clean['operator'].notna()
        print(df_clean[newly_filled][['name', 'operator', 'state_abb']].head(10))
    
    # 4. HANDLE MISSING NAMES
    print("\n4. Handling missing names...")
    missing_names_before = df_clean['name'].isnull().sum()
    print(f"   Records with missing names: {missing_names_before}")
    
    # Strategy: Use operator if available, otherwise create descriptive name
    def create_name(row):
        if pd.notna(row['name']):
            return row['name']
        elif pd.notna(row['operator']):
            return f"{row['operator']} Data Center"
        else:
            return f"{row['county']} Data Center"
    
    df_clean['name'] = df_clean.apply(create_name, axis=1)
    
    missing_names_after = df_clean['name'].isnull().sum()
    print(f"   Filled {missing_names_before - missing_names_after} missing names")
    if (missing_names_before - missing_names_after) > 0:
        print(f"   Sample generated names:")
        generated_mask = df_clean['name'].str.contains('Data Center', na=False)
        if generated_mask.any():
            print(df_clean[generated_mask][['name', 'operator', 'county', 'state_abb']].head(3))
    
    # 5. CLEAN OPERATOR FIELD
    print("\n5. Standardizing operator names...")
    
    # Standardize common operator name variations
    operator_standardization = {
        'google': 'Google',
        'Google': 'Google',
        'microsoft': 'Microsoft',
        'Microsoft': 'Microsoft',
        'meta': 'Meta',
        'Meta': 'Meta',
        'facebook': 'Meta',
        'Facebook': 'Meta',
        'amazon': 'Amazon',
        'Amazon': 'Amazon',
        'aws': 'Amazon',
        'AWS': 'Amazon',
        'apple': 'Apple',
        'Apple': 'Apple',
        'oracle': 'Oracle',
        'Oracle': 'Oracle',
    }
    
    # Apply standardization
    df_clean['operator'] = df_clean['operator'].replace(operator_standardization, regex=False)
    
    print(f"   Top operators after standardization:")
    print(df_clean['operator'].value_counts().head(15))
    
    # 6. STANDARDIZE TYPE FIELD
    print("\n6. Standardizing type field...")
    print(f"   Type values before:")
    print(f"   {df_clean['type'].value_counts()}")
    
    # Standardize capitalization
    df_clean['type'] = df_clean['type'].str.capitalize()
    
    print(f"   Type values after:")
    print(f"   {df_clean['type'].value_counts()}")
    
    # 7. VALIDATE AND CLEAN SIZE DATA
    print("\n7. Validating facility size (sqft)...")
    print(f"   Missing sqft: {df_clean['sqft'].isnull().sum()}")
    print(f"   Sqft statistics:")
    print(df_clean['sqft'].describe())
    
    # Flag potentially unrealistic sizes
    very_small = df_clean['sqft'] < 1000
    very_large = df_clean['sqft'] > 10000000
    
    if very_small.any():
        print(f"\n   WARNING: {very_small.sum()} facilities < 1,000 sqft (possibly data entry errors)")
        print(df_clean[very_small][['id', 'name', 'operator', 'sqft', 'type']].head())
    
    if very_large.any():
        print(f"\n   WARNING: {very_large.sum()} facilities > 10M sqft (check if valid)")
        print(df_clean[very_large][['id', 'name', 'operator', 'sqft', 'type']].head())
    
    # Create size categories
    def categorize_size(sqft):
        if pd.isna(sqft):
            return 'Unknown'
        elif sqft < 10000:
            return 'Very Small (<10k sqft)'
        elif sqft < 50000:
            return 'Small (10k-50k sqft)'
        elif sqft < 100000:
            return 'Medium (50k-100k sqft)'
        elif sqft < 500000:
            return 'Large (100k-500k sqft)'
        elif sqft < 1000000:
            return 'Very Large (500k-1M sqft)'
        else:
            return 'Mega (>1M sqft)'
    
    df_clean['size_category'] = df_clean['sqft'].apply(categorize_size)
    print(f"\n   Size categories:")
    print(df_clean['size_category'].value_counts())
    
    # 8. VALIDATE COORDINATES
    print("\n8. Validating coordinates...")
    
    # Check for missing coordinates (should be none based on initial assessment)
    missing_coords = df_clean['lat'].isnull() | df_clean['lon'].isnull()
    if missing_coords.any():
        print(f"   ERROR: {missing_coords.sum()} records with missing coordinates")
        print(df_clean[missing_coords][['id', 'name', 'state', 'county']])
    
    # Validate coordinate ranges for US territories (expanded to include all territories)
    state_bounds = {
        'HI': {'lat_min': 18, 'lat_max': 23, 'lon_min': -161, 'lon_max': -154},
        'AK': {'lat_min': 51, 'lat_max': 72, 'lon_min': -180, 'lon_max': -130},
        'PR': {'lat_min': 17.5, 'lat_max': 18.5, 'lon_min': -67.5, 'lon_max': -65.0},  # Puerto Rico
        'VI': {'lat_min': 17.5, 'lat_max': 18.5, 'lon_min': -65.0, 'lon_max': -64.5},  # US Virgin Islands
        'GU': {'lat_min': 13.0, 'lat_max': 14.0, 'lon_min': 144.5, 'lon_max': 145.5},  # Guam
        'AS': {'lat_min': -14.5, 'lat_max': -14.0, 'lon_min': -171.0, 'lon_max': -169.0},  # American Samoa
        'MP': {'lat_min': 14.0, 'lat_max': 21.0, 'lon_min': 144.0, 'lon_max': 146.0},  # Northern Mariana Islands
        'default': {'lat_min': 24, 'lat_max': 50, 'lon_min': -125, 'lon_max': -65}  # Contiguous US
    }
    
    def check_coord_validity(row):
        """Check if coordinates are valid for the state/territory"""
        state = row['state_abb']
        lat = row['lat']
        lon = row['lon']
        
        # Get appropriate bounds
        bounds = state_bounds.get(state, state_bounds['default'])
        
        in_range = (bounds['lat_min'] <= lat <= bounds['lat_max'] and 
                   bounds['lon_min'] <= lon <= bounds['lon_max'])
        
        return in_range
    
    invalid_coords = ~df_clean.apply(check_coord_validity, axis=1)
    
    if invalid_coords.any():
        print(f"   WARNING: {invalid_coords.sum()} records with coordinates outside expected state bounds")
        print(df_clean[invalid_coords][['id', 'name', 'state_abb', 'county', 'lat', 'lon']])
        print("   Note: These may be valid but in unexpected locations - review manually")
    else:
        print("   All coordinates are within expected bounds for their states/territories")
    
    # 9. CHECK FOR DUPLICATE COORDINATES (multiple facilities at same location)
    print("\n9. Checking for duplicate coordinates...")
    coord_groups = df_clean.groupby(['lat', 'lon']).size()
    duplicates = coord_groups[coord_groups > 1]
    
    if len(duplicates) > 0:
        print(f"   Found {len(duplicates)} coordinate pairs with multiple facilities")
        print(f"   Total facilities sharing coordinates: {duplicates.sum()}")
        print("\n   Sample locations with multiple facilities:")
        
        for (lat, lon), count in duplicates.head(3).items():
            print(f"\n   Location ({lat:.4f}, {lon:.4f}): {count} facilities")
            facilities = df_clean[(df_clean['lat'] == lat) & (df_clean['lon'] == lon)]
            print(facilities[['id', 'name', 'operator', 'type', 'sqft']])
    else:
        print("   No duplicate coordinates found")
    
    # 10. VALIDATE STATE CONSISTENCY
    print("\n10. Validating state data...")
    
    # Check if state and state_abb are consistent
    state_mapping = df_clean.groupby('state')['state_abb'].unique()
    inconsistent = [s for s in state_mapping.index if len(state_mapping[s]) > 1]
    
    if inconsistent:
        print(f"   WARNING: Inconsistent state/state_abb mappings for: {inconsistent}")
        for state in inconsistent:
            print(f"      {state}: {state_mapping[state]}")
    else:
        print("   State/state_abb mappings are consistent")
    
    print(f"\n   Facilities by state/territory (top 10):")
    print(df_clean['state'].value_counts().head(10))
    
    # 11. CREATE DATA QUALITY FLAGS
    print("\n11. Creating data quality flags...")
    df_clean['has_operator'] = df_clean['operator'].notna()
    df_clean['operator_extracted'] = mask_missing_operator & df_clean['operator'].notna()  # Track extracted operators
    df_clean['has_size'] = df_clean['sqft'].notna()
    df_clean['has_ref'] = df_clean['ref'].notna()
    df_clean['is_campus'] = df_clean['type'] == 'Campus'
    df_clean['is_building'] = df_clean['type'] == 'Building'
    df_clean['name_is_generated'] = df_clean['name'].str.contains('Data Center', na=False)
    
    # Overall data completeness score (0-3)
    df_clean['data_completeness'] = (
        df_clean['has_operator'].astype(int) +
        df_clean['has_size'].astype(int) +
        df_clean['has_ref'].astype(int)
    )
    
    print(f"\n   Data quality summary:")
    print(f"   Records with operator: {df_clean['has_operator'].sum()} ({df_clean['has_operator'].sum()/len(df_clean)*100:.1f}%)")
    print(f"   Operators extracted from name: {df_clean['operator_extracted'].sum()}")
    print(f"   Records with size: {df_clean['has_size'].sum()} ({df_clean['has_size'].sum()/len(df_clean)*100:.1f}%)")
    print(f"   Records with reference: {df_clean['has_ref'].sum()} ({df_clean['has_ref'].sum()/len(df_clean)*100:.1f}%)")
    print(f"   Campus type: {df_clean['is_campus'].sum()}")
    print(f"   Building type: {df_clean['is_building'].sum()}")
    print(f"\n   Data completeness distribution:")
    print(df_clean['data_completeness'].value_counts().sort_index())
    
    print(f"\nFinal shape: {df_clean.shape}")
    
    return df_clean

# Run the cleaning
dc_osdc_clean = clean_osdc(dc_osdc)

# 1. STANDARDIZE COLUMN NAMES
dc_osdc_clean = dc_osdc_clean.rename(columns={
    'lon': 'longitude',
    'lat': 'latitude',
    'sqft': 'facility_size_sqft'
})


# Save cleaned version
dc_osdc_clean.to_csv('/Users/zdiener/data-center-classification/data/processed/osdc_cleaned.csv', index=False)
print("\nCleaned OSDC data saved to: data/processed/osdc_cleaned.csv")

# Show summary comparison
print("\n" + "="*60)
print("OSDC CLEANING SUMMARY")
print("="*60)
print(f"\nOriginal records: {len(dc_osdc)}")
print(f"Cleaned records: {len(dc_osdc_clean)}")
print(f"\nMissing data handled:")
print(f"  Names: {dc_osdc['name'].isnull().sum()} -> {dc_osdc_clean['name'].isnull().sum()}")
print(f"  Operators: {dc_osdc['operator'].isnull().sum()} (kept as-is)")
print(f"  Sqft: {dc_osdc['sqft'].isnull().sum()} (kept as-is)")
print(f"\nNew fields created:")
print(f"  - size_category")
print(f"  - has_operator, has_size, has_ref")
print(f"  - is_campus, is_building")
print(f"  - name_is_generated")
print(f"  - data_completeness")

Starting OSDC cleaning...
Initial shape: (1242, 13)

1. Checking for duplicates...
   Removed 0 duplicate rows

2. Stripping whitespace from text fields...
   Whitespace stripped from 7 fields

3. Extracting operators from facility names...
   Missing operators before: 458
   Extracted 62 operators from facility names
   Missing operators after: 396

   Sample extracted operators:
                              name       operator state_abb
4       Apple - Maiden Data Center          Apple        NC
12                    CoreSite BO1       CoreSite        MA
52                    IBM Building            IBM        NY
57      CoreSite Reston Campus VA1       CoreSite        VA
61     CyrusOne Cincinnati-Lebanon       CyrusOne        OH
70   Iron Mountain Records Storage  Iron Mountain        AZ
80      Aligned Energy Data Center        Aligned        AZ
85        DataBank Pittsburgh PIT2       DataBank        PA
104    CyrusOne Chicago Aurora CME       CyrusOne        IL
108       DataBank Piscataway EWR2       DataBank        NJ

4. Handling missing names...
   Records with missing names: 213
   Filled 213 missing names
   Sample generated names:
                         name operator           county state_abb
2          Google Data Center   Google  Caldwell County        NC
4  Apple - Maiden Data Center    Apple   Catawba County        NC
6    Meta Henrico Data Center     Meta   Henrico County        VA

5. Standardizing operator names...
   Top operators after standardization:
operator
Amazon Web Services            176
Digital Realty                  71
Meta                            63
Google                          60
Microsoft                       54
Flexential                      42
Equinix                         39
CyrusOne                        31
Quality Technology Services     24
CoreSite                        17
NTT                             16
Iron Mountain                   12
Switch                          12
Lumen Technologies              10
Apple                            8
Name: count, dtype: int64

6. Standardizing type field...
   Type values before:
   type
building    1040
campus       109
point         93
Name: count, dtype: int64
   Type values after:
   type
Building    1040
Campus       109
Point         93
Name: count, dtype: int64

7. Validating facility size (sqft)...
   Missing sqft: 93
   Sqft statistics:
count    1.149000e+03
mean     4.742561e+05
std      1.971704e+06
min      2.040000e+02
25%      5.809500e+04
50%      1.323880e+05
75%      2.319240e+05
max      2.659752e+07
Name: sqft, dtype: float64

   WARNING: 5 facilities < 1,000 sqft (possibly data entry errors)
              id                         name operator   sqft      type
267    358946546                QES Computers      NaN  941.0  Building
655    812630939                      Comcast  Comcast  953.0  Building
915   1133944585   Madison County Data Center      NaN  204.0  Building
975   1211362828  Columbia County Data Center      NaN  361.0  Building
1082  1296723872                         GVTC     GVTC  446.0  Building

   WARNING: 12 facilities > 10M sqft (check if valid)
            id                            name   operator        sqft    type
3     13924557                Project Alluvion  Microsoft  10962475.0  Campus
9     18518989     Meta Huntsville Data Center       Meta  14138187.0  Campus
375  460087665  Facebook Prineville Datacenter       Meta  15867920.0  Campus
451  545730285    Facebook Altoona Data Center       Meta  20353917.0  Campus
469  578393557     Apple Prineville Datacenter      Apple  15637209.0  Campus

   Size categories:
size_category
Large (100k-500k sqft)       585
Small (10k-50k sqft)         218
Medium (50k-100k sqft)       181
Unknown                       93
Mega (>1M sqft)               69
Very Large (500k-1M sqft)     54
Very Small (<10k sqft)        42
Name: count, dtype: int64

8. Validating coordinates...
   All coordinates are within expected bounds for their states/territories

9. Checking for duplicate coordinates...
   Found 2 coordinate pairs with multiple facilities
   Total facilities sharing coordinates: 4

   Sample locations with multiple facilities:

   Location (33.7466, -84.5797): 2 facilities
            id                          name        operator      type  \
773  975064000  Digital Realty Atlanta ATL11  Digital Realty  Building
774  975064000  Digital Realty Atlanta ATL11  Digital Realty  Building

         sqft
773  313479.0
774  313479.0

   Location (41.4982, -93.7886): 2 facilities
            id            name   operator    type       sqft
683  830885779  Project Osmium  Microsoft  Campus  3691114.0
684  830885779  Project Osmium  Microsoft  Campus  3691114.0

10. Validating state data...
   State/state_abb mappings are consistent

   Facilities by state/territory (top 10):
state
Virginia      292
California     94
Oregon         94
Texas          92
Washington     81
Iowa           57
Ohio           56
Arizona        54
New Jersey     47
Illinois       41
Name: count, dtype: int64

11. Creating data quality flags...

   Data quality summary:
   Records with operator: 846 (68.1%)
   Operators extracted from name: 62
   Records with size: 1149 (92.5%)
   Records with reference: 327 (26.3%)
   Campus type: 109
   Building type: 1040

   Data completeness distribution:
data_completeness
0     44
1    377
2    518
3    303
Name: count, dtype: int64

Final shape: (1242, 22)

Cleaned OSDC data saved to: data/processed/osdc_cleaned.csv

============================================================
OSDC CLEANING SUMMARY
============================================================

Original records: 1242
Cleaned records: 1242

Missing data handled:
  Names: 213 -> 0
  Operators: 458 (kept as-is)
  Sqft: 93 (kept as-is)

New fields created:
  - size_category
  - has_operator, has_size, has_ref
  - is_campus, is_building
  - name_is_generated
  - data_completeness